# Generated by Django 4.2.7 on 2023-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date_enrolled', models.DateField()),
                ('time_slot', models.TimeField()),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'bike'), ('SCOOTER', 'scooter'), ('CAR', 'car'), ('OTHER', 'other')], default='BIKE', max_length=9)),
                ('final_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
