# Generated by Django 4.2.7 on 2023-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('HOLD', 'hold'), ('FINISHED', 'finished')], default='ACTIVE', max_length=9),
        ),
    ]
