# Generated by Django 4.2.7 on 2023-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'paid'), ('PARTIALLY PAID', 'partially paid'), ('UNPAID', 'unpaid')], default='UNPAID', max_length=30),
        ),
    ]
