# Generated by Django 4.2.7 on 2023-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_student_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('tutor_type', models.CharField(choices=[('BIKE/SCOOTER', 'bike/scooter'), ('CAR', 'car'), ('ALL', 'all'), ('OTHER', 'other')], default='BIKE/SCOOTER', max_length=50)),
            ],
        ),
    ]
