# Generated by Django 4.2.7 on 2023-11-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
    ]
