# Generated by Django 4.2.7 on 2023-11-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_staff_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='staff_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_assigned', to='management.staffs'),
        ),
    ]
